Repository kakao-tech-campus-2nd-step3/Team23_BE, pull requests merged in 2024-09, with the labels that each got.

#5 Chore/issue#2: CD 스크립트 작성
  .github/workflows/cd.yml
  Dockerfile
  build.gradle
  gradlew
Labels: 🌏 Deploy

#13 Chore/issue#12: 프로젝트 Set Up
  build.gradle
  src/main/java/kappzzang/jeongsan/Application.java
  src/main/java/kappzzang/jeongsan/config/SwaggerConfig.java
  src/main/java/kappzzang/jeongsan/domain/BaseEntity.java
  src/main/java/kappzzang/jeongsan/domain/Category.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/domain/Item.java
  src/main/java/kappzzang/jeongsan/domain/KakaoToken.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/domain/Team.java
  src/main/java/kappzzang/jeongsan/domain/TeamMember.java
  src/main/java/kappzzang/jeongsan/enumeration/Status.java
Labels: ⚙ Setting

#19 Feature/issue#14: custom api response, exception handler 구현
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  build.gradle
  src/main/java/kappzzang/jeongsan/controller/ExampleController.java
  src/main/java/kappzzang/jeongsan/domain/BaseEntity.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/global/common/JeongsanApiResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/Status.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/global/config/SwaggerConfig.java
  src/main/java/kappzzang/jeongsan/global/exception/GlobalExceptionHandler.java
  src/main/java/kappzzang/jeongsan/global/exception/JeongsanException.java
  src/test/java/kappzzang/jeongsan/controller/ExampleControllerTest.java
Labels: ✨ Feature

#20 Feature/issue#16: 모임 목록 조회 기능 구현
  src/main/java/kappzzang/jeongsan/Application.java
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/dto/MemberPreview.java
  src/main/java/kappzzang/jeongsan/dto/response/TeamResponse.java
  src/main/java/kappzzang/jeongsan/repository/TeamRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
Labels: ✨ Feature

#22 Feature/issue#15 영수증 OCR Api 구현
  build.gradle
  src/main/java/kappzzang/jeongsan/Application.java
  src/main/java/kappzzang/jeongsan/controller/ReceiptController.java
  src/main/java/kappzzang/jeongsan/dto/Image.java
  src/main/java/kappzzang/jeongsan/dto/ItemSummary.java
  src/main/java/kappzzang/jeongsan/dto/request/ChatGptRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/GeneralOcrRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/ChatGptResponse.java
  src/main/java/kappzzang/jeongsan/dto/response/GeneralOcrResponse.java
  src/main/java/kappzzang/jeongsan/dto/response/ParsedReceiptResponse.java
  src/main/java/kappzzang/jeongsan/global/client/clova/ClovaApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/clova/ClovaOcrProperties.java
  src/main/java/kappzzang/jeongsan/global/client/openai/GptPromptManager.java
  src/main/java/kappzzang/jeongsan/global/client/openai/OpenAiApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/openai/OpenAiProperties.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/global/config/ApiClientConfig.java
  src/main/java/kappzzang/jeongsan/global/interceptor/LoggingInterceptor.java
  src/main/java/kappzzang/jeongsan/service/ReceiptService.java
  src/main/resources/application.properties
  src/main/resources/prompts/gpt_instruction.txt
  src/test/java/kappzzang/jeongsan/global/client/ClovaApiClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/OpenAiApiClientTest.java
Labels: ✨ Feature

#30 Fix: 배포 스크립트에서 빌드된 jar 파일을 읽지 못하는 오류 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🐞 Bug, 🌏 Deploy
