Repository kakao-tech-campus-2nd-step3/Team23_BE, pull requests merged in 2024-10, with the labels that each got.

#33 Feature/issue#17: JWT 인증/인가
  build.gradle
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
  src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationFilter.java
  src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationProvider.java
  src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationToken.java
  src/main/java/kappzzang/jeongsan/global/util/JwtUtil.java
Labels: ✨ Feature

#43 Feature/issue#21: 지출 목록 (정산 중, 완료) 조회 기능 구현
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/dto/CategoryDto.java
  src/main/java/kappzzang/jeongsan/dto/response/ExpenseResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/repository/ItemRepository.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
Labels: ✨ Feature

#45 Feature/issue#32: S3 이미지 저장 기능 구현
  .github/workflows/ci.yml
  build.gradle
  src/main/java/kappzzang/jeongsan/global/client/aws/AwsClient.java
  src/main/java/kappzzang/jeongsan/global/client/aws/AwsS3Properties.java
  src/main/java/kappzzang/jeongsan/global/client/clova/ClovaApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/dto/request/ChatGptRequest.java
  src/main/java/kappzzang/jeongsan/global/client/dto/request/GeneralOcrRequest.java
  src/main/java/kappzzang/jeongsan/global/client/dto/request/UploadImageRequest.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/ChatGptResponse.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/GeneralOcrResponse.java
  src/main/java/kappzzang/jeongsan/global/client/openai/OpenAiApiClient.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/config/S3ClientConfig.java
  src/main/java/kappzzang/jeongsan/global/interceptor/AwsClientLoggingInterceptor.java
  src/main/java/kappzzang/jeongsan/service/ImageStorageService.java
  src/main/java/kappzzang/jeongsan/service/ReceiptService.java
  src/test/java/kappzzang/jeongsan/global/client/AwsClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/ClovaApiClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/OpenAiApiClientTest.java
  src/test/java/kappzzang/jeongsan/service/ImageStorageServiceTest.java
Labels: ✨ Feature

#44 Feature/issue#41: 카카오 토큰을 이용한 로그인
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/dto/request/LoginRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoProfileProperties.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/global/config/ApiClientConfig.java
  src/main/java/kappzzang/jeongsan/global/util/JwtUtil.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/global/client/KakaoApiClientTest.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: ✨ Feature

#48 Document/issue#46: 지출 내역 및 모임 관련 API에 대한 명세 작성
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
Labels: 📃 Docs

#49 Feat: ECS 배포 설정
  .github/workflows/ci-cd.yml
Labels: 🌏 Deploy

#50 Feature/issue#47: 지출 내역(결제자) 등록 기능 구현
  src/main/java/kappzzang/jeongsan/controller/ReceiptController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/domain/Item.java
  src/main/java/kappzzang/jeongsan/dto/Image.java
  src/main/java/kappzzang/jeongsan/dto/ItemSummary.java
  src/main/java/kappzzang/jeongsan/dto/request/SaveExpenseRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/SaveExpenseResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/global/exception/GlobalExceptionHandler.java
  src/main/java/kappzzang/jeongsan/repository/CategoryRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/main/java/kappzzang/jeongsan/service/ImageStorageService.java
Labels: ✨ Feature

#59 Refactor/issue#57: 중복 스크립트 삭제 및 빌드 과정에서 테스트 제외
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: 🌏 Deploy, 🔨 Refactor

#62 Refactor/issue#60: 변경 사항에 맞춰 엔티티 클래스 수정
  src/main/java/kappzzang/jeongsan/domain/KakaoPayInfo.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
Labels: 🔨 Refactor

#64 Feature/issue#58: 지출 상세 내역 조회 기능 구현
  src/main/java/kappzzang/jeongsan/controller/ReceiptController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/domain/Item.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/ItemDetail.java
  src/main/java/kappzzang/jeongsan/dto/request/ChatGptRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/GeneralOcrRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/ChatGptResponse.java
  src/main/java/kappzzang/jeongsan/dto/response/GeneralOcrResponse.java
  src/main/java/kappzzang/jeongsan/dto/response/PersonalExpenseDetailResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/main/java/kappzzang/jeongsan/service/ImageStorageService.java
  src/test/java/kappzzang/jeongsan/global/client/AwsClientTest.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
  src/test/java/kappzzang/jeongsan/service/ImageStorageServiceTest.java
Labels: ✨ Feature

#56 Feature/issue#55: 모임의 멤버 초대 현황 조회 API
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/TeamMember.java
  src/main/java/kappzzang/jeongsan/dto/response/InvitationStatusResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/TeamMemberRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: ✨ Feature

#66 Feature/issue#61: Refresh 토큰 추가
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
  src/main/java/kappzzang/jeongsan/global/util/JwtProperties.java
  src/main/java/kappzzang/jeongsan/global/util/JwtUtil.java
  src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/global/client/KakaoApiClientTest.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: ✨ Feature

#68 Feature/issue#67: 모임 생성 기능 추가
  build.gradle
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Team.java
  src/main/java/kappzzang/jeongsan/dto/request/CreateTeamRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/CreateTeamResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/repository/TeamRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: ✨ Feature

#69 Docs: 에러코드 정리 및 6주차 코드 리뷰 질문
  CodeReview/images/image_1.png
  CodeReview/week6.md
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/util/JwtProperties.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
Labels: 📃 Docs, 🔍 Review

#75 Refactor/issue#74: Item, PersonalExpense 엔티티 연관관계 수정
  src/main/java/kappzzang/jeongsan/domain/Item.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
Labels: 🔨 Refactor

#76 Refactor/issue#73: 엔티티 클래스 수정
  src/main/java/kappzzang/jeongsan/domain/BaseEntity.java
  src/main/java/kappzzang/jeongsan/domain/Category.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/domain/Item.java
  src/main/java/kappzzang/jeongsan/domain/KakaoPayInfo.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/domain/Team.java
  src/main/java/kappzzang/jeongsan/domain/TeamMember.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
Labels: 🔨 Refactor

#79 Refactor/issue#77: TestUtil 및 주석 처리된 레포지토리 테스트 코드 수정
  src/main/java/kappzzang/jeongsan/domain/Category.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
Labels: 🔨 Refactor

#88 Chore/issue#81: Weekly 브랜치 기준 서버 배포 자동화
  .github/workflows/test-deploy.yml
Labels: 🌏 Deploy

#90 Chore/issue#81;FIX: ssh 키 호출 에러 해결을 위해 키파일 생성 후 삭제 방식으로 변경
  .github/workflows/test-deploy.yml
Labels: 🐞 Bug, 🌏 Deploy

#85 Feature/issue#84: `closeTeam` 명세 변경에 따른 request body 삭제
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Team.java
  src/main/java/kappzzang/jeongsan/dto/request/CloseTeamRequest.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
Labels: ✨ Feature

#96 Feature/issue#78: 지출 상태 변경(송금 대기 -> 완료) 기능 구현
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/dto/request/CompleteExpensesRequest.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
Labels: ✨ Feature

#98 Refactor: Status에 따른 지출 내역 조회를 Map을 이용하도록 수정
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
Labels: 🔨 Refactor
