Repository kakao-tech-campus-2nd-step3/Team23_BE, pull requests merged in 2024-11, with the labels that each got.

#101 Feature/issue#100: 카카오 페이 송금 링크 조회 API 구현
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/KakaoPayInfo.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/dto/response/GetPayLinkResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: ✨ Feature

#99 Feature/issue#86 : 개인 소비 내역 저장 API 구현
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/request/SavePersonalExpenseRequest.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/PersonalExpenseService.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: ✨ Feature

#104 Feature/issue#95: 회원가입 API 추가
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/dto/request/LoginRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/RegisterRequest.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoProfileProperties.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/global/client/KakaoApiClientTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: ✨ Feature

#108 [23조 KAPP짱 - BE] 9 주차 코드리뷰
  CodeReview/week3.md
  CodeReview/week5.md
  CodeReview/week6.md
  CodeReview/week9.md
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/domain/KakaoPayInfo.java
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/request/CompleteExpensesRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/LoginRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/RegisterRequest.java
  src/main/java/kappzzang/jeongsan/dto/request/SavePersonalExpenseRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/GetPayLinkResponse.java
  src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoProfileProperties.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/main/java/kappzzang/jeongsan/service/PersonalExpenseService.java
  src/test/java/kappzzang/jeongsan/global/client/KakaoApiClientTest.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: 🔍 Review

#121 Chore/issue#120: Swagger에 배포 주소 추가, CI 스크립트 수정
  .github/workflows/weekly-ci.yml
  src/main/java/kappzzang/jeongsan/global/config/SwaggerConfig.java
Labels: ⚙ Setting

#125 Docs: issue 자동 종료가 실행되도록 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#119 Fix/issue#118: 회원가입 시 회원 정보가 두 번 저장되는 현상 수정
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/global/config/ApiClientConfig.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: 🐞 Bug

#132 Feature/issue#130: Member 도메인에 카카오 UUID 추가
  src/main/java/kappzzang/jeongsan/domain/Member.java
  src/main/java/kappzzang/jeongsan/dto/request/RegisterRequest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: ✨ Feature

#126 Refactor: 사용되지 않는 어노테이션, 생성자 제거 및 기타 리펙토링
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/ItemSummary.java
  src/main/java/kappzzang/jeongsan/dto/request/SaveExpenseRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/SaveExpenseResponse.java
  src/main/java/kappzzang/jeongsan/global/client/clova/ClovaApiClient.java
  src/main/java/kappzzang/jeongsan/global/client/openai/OpenAiApiClient.java
  src/test/java/kappzzang/jeongsan/global/client/ClovaApiClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/OpenAiApiClientTest.java
Labels: 🔨 Refactor

#127 Feature/issue#112: 카테고리 목록 조회 기능 구현
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/dto/response/CategoryListResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/service/CategoryService.java
  src/test/java/kappzzang/jeongsan/service/CategoryServiceTest.java
Labels: ✨ Feature

#133 Refactor/issue#131: 멤버 정보 리스트 타입 수정
  src/main/java/kappzzang/jeongsan/dto/request/CreateTeamRequest.java
  src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: 🔨 Refactor

#134 Chore/issue#123: 테스트 서버(베타 서버) DB 분리
  .github/workflows/test-deploy.yml
Labels: 🌏 Deploy, ⚙ Setting

#117 Feature/issue#102: 송금 요청 대상과 금액 조회
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/dto/request/TransferTargetRequest.java
  src/main/java/kappzzang/jeongsan/dto/response/TransferTargetResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/repository/PersonalExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/GetTransferTargetTest.java
Labels: ✨ Feature

#135 Feature/issue#128: Swagger에서 같은 코드의 여러 에러 응답을 볼 수 있도록 수정
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/global/common/ApiErrorTypeExample.java
  src/main/java/kappzzang/jeongsan/global/config/SwaggerConfig.java
  src/main/java/kappzzang/jeongsan/global/swagger/ErrorResponse.java
  src/main/java/kappzzang/jeongsan/global/swagger/ExampleHolder.java
Labels: ✨ Feature

#141 Refactor/issue#137: Chat GPT API 요청 형식 수정
  src/main/java/kappzzang/jeongsan/global/client/dto/request/ChatGptRequest.java
  src/main/java/kappzzang/jeongsan/global/client/openai/OpenAiApiClient.java
  src/main/java/kappzzang/jeongsan/global/config/ApiClientConfig.java
Labels: 🔨 Refactor

#146 Refactor/issue#140: 지출 상태 변경 API 수정
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/dto/request/ChangeExpensesStateRequest.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/Status.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
Labels: 🔨 Refactor

#136 Feature/issue#110: 대기 상태 지출 목록 조회 API
  src/main/java/kappzzang/jeongsan/dto/ExpenseWithPersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/response/ExpenseResponse.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
Labels: ✨ Feature

#147 Feature/issue#143: owner만 모임을 종료할 수 있도록 변경
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Team.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
Labels: ✨ Feature

#144 Feature/issue#139: 지출 선택 상세 내역 조회 API 구현
  src/main/java/kappzzang/jeongsan/controller/ReceiptController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/Expense.java
  src/main/java/kappzzang/jeongsan/dto/response/ExpenseDetailResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/test/java/kappzzang/jeongsan/service/GetExpenseDetailResponseTest.java
Labels: ✨ Feature

#159 Feature/issue#154: 모임 멤버 아이디 조회 API
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/dto/response/MemberIdResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/TeamMemberRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: ✨ Feature

#155 Fix/issue#152: JWT 관련 에러 처리 및 경로 설정
  src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
  src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationFilter.java
Labels: 🐞 Bug

#163 Fix/issue#162: 모임 멤버 아이디 조회 시 카카오 아이디를 응답하도록 수정
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/dto/response/MemberIdResponse.java
  src/main/java/kappzzang/jeongsan/dto/response/MemberKakaoIdResponse.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
  src/main/java/kappzzang/jeongsan/repository/TeamMemberRepository.java
  src/main/java/kappzzang/jeongsan/service/TeamService.java
  src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: 🐞 Bug

#168 Fix/issue#167: TransferTargetRequest의 expense null 문제 해결
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
Labels: 🐞 Bug

#164 Feature/issue#145: 개인 소비 내역 수정
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/dto/CalculatedPrice.java
  src/main/java/kappzzang/jeongsan/dto/request/SavePersonalExpenseRequest.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/service/PersonalExpenseService.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: ✨ Feature

#175 Fix/issue#169: Access 토큰 재발급 과정에서 인증 과정 생략
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/global/util/JwtUtil.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: 🐞 Bug

#172 Test/issue#171: 기존 테스트 코드 리펙토링 및 Repository, Domain Test 추가
  src/test/java/kappzzang/jeongsan/domain/ExpenseTest.java
  src/test/java/kappzzang/jeongsan/global/client/AwsClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/ClovaApiClientTest.java
  src/test/java/kappzzang/jeongsan/global/client/OpenAiApiClientTest.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/PersonalExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
  src/test/java/kappzzang/jeongsan/service/ImageStorageServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#184 Test/issue#179: Team 도메인 테스트 추가
  src/test/java/kappzzang/jeongsan/domain/TeamTest.java
Labels: ✅ Test

#186 Refactor/issue#183: 송금 대상 및 금액 조회 수정
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/test/java/kappzzang/jeongsan/repository/PersonalExpenseRepositoryTest.java
Labels: 🔨 Refactor

#181 Refactor/issue#180: Expense 상태가 송금 대기로 변경될 때 개인 지출 금액을 산출하도록 수정
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/domain/PersonalExpense.java
  src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
  src/main/java/kappzzang/jeongsan/repository/ExpenseRepository.java
  src/main/java/kappzzang/jeongsan/repository/PersonalExpenseRepository.java
  src/main/java/kappzzang/jeongsan/service/ExpenseService.java
  src/test/java/kappzzang/jeongsan/repository/ExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpensePriceCalculateTest.java
Labels: ✨ Feature, 🔨 Refactor

#189 Refactor/issue#188: 패키지 구조 변경
  src/main/java/kappzzang/jeongsan/controller/ExampleController.java
  src/main/java/kappzzang/jeongsan/controller/ExpenseController.java
  src/main/java/kappzzang/jeongsan/controller/MemberController.java
  src/main/java/kappzzang/jeongsan/controller/ReceiptController.java
  src/main/java/kappzzang/jeongsan/controller/TeamController.java
  src/main/java/kappzzang/jeongsan/controller/docs/ExpenseControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/MemberControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/ReceiptControllerInterface.java
  src/main/java/kappzzang/jeongsan/controller/docs/TeamControllerInterface.java
  src/main/java/kappzzang/jeongsan/global/common/annotation/ApiErrorTypeExample.java
  src/main/java/kappzzang/jeongsan/global/common/dto/JeongsanApiResponse.java
  src/main/java/kappzzang/jeongsan/global/common/security/JwtAuthenticationFilter.java
  src/main/java/kappzzang/jeongsan/global/common/security/JwtAuthenticationProvider.java
  src/main/java/kappzzang/jeongsan/global/common/security/JwtAuthenticationToken.java
  src/main/java/kappzzang/jeongsan/global/common/swagger/ErrorResponse.java
  src/main/java/kappzzang/jeongsan/global/common/swagger/ExampleHolder.java
  src/main/java/kappzzang/jeongsan/global/common/util/JwtProperties.java
  src/main/java/kappzzang/jeongsan/global/common/util/JwtUtil.java
  src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
  src/main/java/kappzzang/jeongsan/global/config/SwaggerConfig.java
  src/main/java/kappzzang/jeongsan/global/exception/GlobalExceptionHandler.java
  src/main/java/kappzzang/jeongsan/service/MemberService.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: 🔨 Refactor

#192 Test/issue#173: 테스트 코드 수정 및 추가
  src/test/java/kappzzang/jeongsan/domain/TeamMemberTest.java
  src/test/java/kappzzang/jeongsan/repository/PersonalExpenseRepositoryTest.java
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest.java
  src/test/java/kappzzang/jeongsan/service/PersonalExpenseServiceTest.java
Labels: ✅ Test

#204 Refactor/issue#203: UpdateExpenseStateTest 수정
  src/test/java/kappzzang/jeongsan/service/ExpenseServiceTest/UpdateExpensesStateTest.java
Labels: 🔨 Refactor, ✅ Test

#201 Test/issue#176: 회원가입, 로그인 테스트 리팩토링 및 통합 테스트 추가
  src/test/java/kappzzang/jeongsan/controller/MemberControllerTest.java
  src/test/java/kappzzang/jeongsan/service/MemberServiceTest.java
Labels: ✅ Test

#208 Test/issue#207: 영수증 분석 기능 통합 테스트 작성
  build.gradle
  src/test/java/kappzzang/jeongsan/integration/ReceiptAnalyzeIntegrationTest.java
Labels: ✅ Test

#206 Test/issue#202: Team 도메인으로의 책임 이동으로 인해 `TeamService.createTeam()`에 대한 테스트 삭제
  src/test/java/kappzzang/jeongsan/service/TeamServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#215 Test/issue#214: 지출 저장 기능 통합 테스트 작성
  src/test/java/kappzzang/jeongsan/integration/SaveExpenseIntegrationTest.java
  src/test/java/kappzzang/jeongsan/repository/TestDataUtil.java
Labels: ✅ Test

#211 Refactor/issue#210: 테스트 코드 패키지 위치 수정
  src/test/java/kappzzang/jeongsan/e2e/MemberAuthenticationE2ETest.java
  src/test/java/kappzzang/jeongsan/e2e/ReceiptAnalyzeE2ETest.java
Labels: 🔨 Refactor
